# Site settings
title: Great New Blog Title
author:
  name: Vera Kryuchkova
  email: vera.v.kruchkova@yandex.ru
description: "Great site about Jekyll on GH-Pages."

# Build settings
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# remote_theme: pages-themes/architect@v0.2.0
remote_theme: jekyll/architect
show_downloads: true
