# Site settings
title: Great New Blog Title
author:
  name: Vera Kryuchkova
  email: vera.v.kruchkova@yandex.ru
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/architect
